# Iterables and iterators

Tuples, lists, sets, and dictionaries are known as *iterables*.

Iterables can produce an iterator.

A nice succinct description can be found here http://stackoverflow.com/questions/9884132/what-exactly-are-pythons-iterator-iterable-and-iteration-protocols...

> Iteration is a general term for taking each item of something, one after another. Any time you use a loop, explicit or implicit, to go over a group of items, that is iteration.

> In Python, iterable and iterator have specific meanings.

> An iterable is an object that has an __iter__ method which returns an iterator, or which defines a __getitem__ method that can take sequential indexes starting from zero (and raises an IndexError when the indexes are no longer valid). So an iterable is an object that you can get an iterator from.

> An iterator is an object with a next (Python 2) or __next__ (Python 3) method.

> Whenever you use a for loop, or map, or a list comprehension, etc. in Python, the next method is called automatically to get each item from the iterator, thus going through the process of iteration.

> A good place to start learning would be the iterators section of the tutorial and the iterator types section of the standard types page. After you understand the basics, try the iterators section of the Functional Programming HOWTO.

https://docs.python.org/3/tutorial/classes.html#iterators
https://docs.python.org/dev/library/stdtypes.html#iterator-types
https://docs.python.org/dev/howto/functional.html#iterators


```python
data = ['one', 'two', 'three']
i = iter(data)
print(next(i))
print(next(i))
print(next(i))
```
[adt01a.py](adt01a.py)

```
$ python adt01a.py
one
two
three
```

```python
data = {'one': 1, 'two': 2, 'three': 3}
i = iter(data)
print(next(i))
print(next(i))
print(next(i))
```
[adt01b.py](adt01b.py)

```
$ python adt01b.py
one
two
three
```

```python
data = ('one', 'two', 'three')
i = iter(data)
print(next(i))
print(next(i))
print(next(i))
print(next(i))
```
[adt01c.py](adt01c.py)

```
$ python adt01c.py
one
two
three
Traceback (most recent call last):
  File "adt01c.py", line 6, in <module>
    print(next(i))
StopIteration
```

An iterator has (in python3) a __next__ method, therefore this can also be written...

```python
data = ('one', 'two', 'three')
i = iter(data)
print(i.__next__())
print(i.__next__())
print(i.__next__())
```
[adt01c1.py](adt01c1.py)

Output...

```
$ python adt01c1.py
one
two
three
```

```python
data1 = ('one', 'two', 'three')
data2 = ('four', 'five', 'six', 'seven')
i = zip(data1, data2) # we create an iter structure of matched pairs
print(">>>>>>>>section1<<<<<<<<<")
print(next(i)) # each call to next moves the pointer
print(next(i))
print(next(i))
print(">>>>>>>>section2<<<<<<<<<")
for a, b, in i: # note that this doesn't print anything (i is exhausted, at end)
    print(a,b)
j = zip(data1, data2) # create a new var, and get a new iter
print(">>>>>>>>section3<<<<<<<<<")
for a, b, in j:  # this one does print out the contents.
    print(a,b)
```
[adt01d.py](adt01d.py)

Output is...

```
$ python adt01d.py
>>>>>>>>section1<<<<<<<<<
('one', 'four')
('two', 'five')
('three', 'six')
>>>>>>>>section2<<<<<<<<<
>>>>>>>>section3<<<<<<<<<
one four
two five
three six
```


Notice from this last example, and iterator can be "exhausted", that is, go to the end of the sequence. The results in throwing an  StopIteration exception (run time error is not caught... we'll be covering exceptions later in the course). BUT, in the case above we don't see this exception, but in the code below we do. This is because in the code above, the for loop in Python catches this error as a signal to indicate it is at the end of the iterator. The code below demonstrates what is occurring in the "background", the for loop is calling next() to iterate through the iterator.

```python
data = ('one', 'two', 'three')
i = iter(data)
print(next(i))
print(next(i))
print(next(i))
print(next(i))
```
[adt01e.py](adt01e.py)

```
$ python adt01e.py
one
two
three
Traceback (most recent call last):
  File "adt01e.py", line 6, in <module>
    print(next(i))
StopIteration

```

So, when our iterator is "exhausted" (at the end of the sequence), the exception is caught by the for loop, so we don't see the error -- we just don't loop...

```python
data = ('one', 'two', 'three')
i = iter(data)
print(">>>>>>>>section1<<<<<<<<<")
print(next(i))
print(next(i))
print(">>>>>>>>section2<<<<<<<<<")
for x in i:
    print(x)
print(">>>>>>>>section3<<<<<<<<<")
for x in i:
    print(x)
```
[adt01e.py](adt01e.py)

```
$ python adt01f.py
>>>>>>>>section1<<<<<<<<<
one
two
>>>>>>>>section2<<<<<<<<<
three
>>>>>>>>section3<<<<<<<<<
```

## How do I know if I have an iterable?

```python
x = [1,2,3]
y = {'one': 1, 'two': 2}
z = 10
print(hasattr(x, '__iter__'))
print(hasattr(y, '__iter__'))
print(hasattr(z, '__iter__'))
```
[adt01g.py](adt01g.py)

```
$ python adt01g.py
True
True
False
```

```python
from collections import Iterable
x = [1,2,3]
y = {'one': 1, 'two': 2}
z = 10
print(isinstance(x,Iterable))
print(isinstance(y,Iterable))
print(isinstance(z,Iterable))
```
[adt01h.py](adt01h.py)

```
$ python adt01h.py
True
True
False
```

As we should see from the above code, the sequence objects (variables x and y) we've looked at are iterables. This means that we can assign (or generate) multiple iterators to the object.


```python
from collections import Iterator, Iterable
x = [1,2,3]
y = {'one': 1, 'two': 2}
z = 10
print(isinstance(x,Iterator))
print(isinstance(y,Iterator))
print(isinstance(z,Iterator))
print(isinstance(iter(x),Iterator))
print(isinstance(iter(y),Iterator))
print(isinstance(iter(z),Iterator))
```
[adt01ha.py](adt01ha.py)

The output of which is....

```
$ python adt01ha.py
False
False
False
True
True
Traceback (most recent call last):
  File "adt01ha.py", line 10, in <module>
    print(isinstance(iter(z),Iterator))
TypeError: 'int' object is not iterable

```

Iterables can produce an iterator (multiple ones), and each iterator holds a position. Iterators will incrementally move to the next position every time next(iteratorVar) is called -- thus allowing us to "iterate" through the elements of the sequence. If we want to 'reset' and iterator, we just create a new one. Once created, an iterator will move to the end, and once there, is exhausted.

__Is a string an iterable?__ (and other similar questions)

Why not try it out and see for yourself....

```python
str = "Hello"
i = iter(str)
j = iter(str)
print(next(i))
print(next(i))
orint(next(j))
```
[adt01h.py](adt01h.py)

... output is..
```
$ python adt01i.py
H
e
H
```

So the answer is, yes. Also, notice how I create two different iterators from the same sequence (string in this case). Each of these iterators have their own state and location within the sequence.
